Music_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: redirect('/bands')

resources :users, only: [:show, :new, :create]

resource :session, only: [:new, :create, :destroy]

resources :bands

end

Music_project/app/models/album.rb
class Album < ApplicationRecord

  validates :name, :band, :year, :live, presence: true
  validates :year, numericality: {minimum: 1900, maximun:9000}
  validates :live, inclusion: { in: [true, false] }
  validates :name, uniqueness: {scope: :band_id}


  belongs_to :band
  has_many :tracks

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end

end

Music_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_project/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy

end

Music_project/app/models/track.rb
class Track < ApplicationRecord

  validates :lyrics, :ord, :title, presence: true
  validates :bonus, inclusion: {in: [true, false]}
  validates :ord, uniqueness: {scope: :album_id}

  belongs_to :album
  has_one :band

  after_initialize :set_defaults

  def set_defaults
    self.bonus ||= false
  end
end

Music_project/app/models/user.rb
# require 'bcrypt'

class User < ApplicationRecord

  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :password_digest, :session_token, presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64(16)
    while self.class.exists?(session_token: token)
      token = SecureRandom.urlsafe_base64
    end
    token
  end

  def self.reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

end

Music_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end


end

Music_project/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def new
      @band = Band.new
      render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save!
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.error.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(user_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

Music_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user
      log_in_user!(user)
      redirect_to  root_url
    else
      flash.now[:errors] = ["Wrong Email and Password!"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

Music_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @users = User.all
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # flash[:notice] = 'Successfully created your account! Check your inbox for an activation email.'
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Music_project/app/helpers/application_helper.rb
module ApplicationHelper
end

Music_project/app/helpers/bands_helper.rb
module BandsHelper
end

Music_project/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music_project/app/helpers/users_helper.rb
module UsersHelper
end

Music_project/app/views/bands/index.html.erb
<div class="main_content">



  <h2 class="page_header">Bands</h2>

  <ul class="">
    <%@bands.each do |band| %>
    <li>
      <a href="<%= band_url(band) %>"><%= band.name %></a>
    </li>
    <% end %>
  </ul>
</div>

Music_project/app/views/bands/new.html.erb
<p>
  New Band!
</p>

Music_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <div class="main_content_app">
      <h1 class="main_logo">Music App</h1>
      <nav>
        <a class="button" href="<%= new_session_url %>">Take me Home</a>
        <div class="user_detail">
          
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

Music_project/app/views/users/new.html.erb
<div class = "main_content">
<h1 class="page_header">New User</h1>

<a class="button" href="<%= new_session_url %>">Go to sign-in</a>

<form class="form" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<p>
  <label>Email</label>
  <input type="email" name="user[email]" value="">
</p>

<p>
  <label>Password</label>
  <input type="password" name="user[password]" value="">
</p>

<input class="button" id="submit_button_2" type="submit" name="" value="Submit">


</form>
</div>

Music_project/app/views/users/show.html.erb
<p class="page_hearder">User Profile</p>

<h2>Email: <%= current_user.email %></h2>